### PR TITLE
Normalize 64-bit flags for easy comparison

### PR DESCRIPTION
**Pull request by techtonik**

### CODE REVIEW

**Comment by techtonik** [comment]
Fetch only mode misses `--buildroot=/tmp/i686` flag. Is that intentional?

**Comment by ogrisel** [comment]
> Fetch only mode misses --buildroot=/tmp/i686 flag. Is that intentional?

Sounds like a bug. @carlkl do you confirm? Or maybe the download does not happen in the tmp folder?

**Comment by carlkl** [comment]
It's a bug: `--buildroot=/tmp/x86_64` is missing in --fetch-only (Build 64-bit toolchain).

**Comment by techtonik** [comment]
Fixed.

**Pull request merged**
