### PR TITLE
MRG: I think this builds correctly on current mingwpy-builds

### PR DESCRIPTION
**Pull request by matthew-brett**
It's still gcc 5.3.0 - but we need a whole new set of patches for more modern
gcc - right?

### CODE REVIEW

**Comment by carlkl** [comment]
@matthew-brett, I prefer to create a new branch with new patches and changes. Some of my changes to nixman's mingw-builds are now obsolete. Stay tuned.

**Comment by carlkl** [comment]
for the sake of corectness: my ast comment refers to your mingw-builds PR.
Fell free to merge your PR yourself. Please tell me if this is not possible for you.

**Comment by carlkl** [comment]
I'm preparing now a new branch with a new set of patches from mingw-builds as well as msys2, so this PR is not needed anymore.

**Comment by matthew-brett** [comment]
Good to hear - thanks.

**Pull request closed without merging**
