### PR TITLE
Finish bootstrap.py

### PR DESCRIPTION
**Pull request by techtonik**
Isolate builds to checkout directory (by forcing cd into it). Without this, bash starts in user $HOME. Fix fetch/build options.

### CODE REVIEW

**Comment by carlkl** [comment]
I would really like to have a bootstrap to easy _install_ msys2 in this special configuration needed for `mingwpy` builds. This makes life simple for anyone willing to reproduce these builds.

But is there a need to install msys2 over an over again for each build? For sure not if you are working with local development. I propose to seperate build commands and msys2 install commands.

**Comment by techtonik** [comment]
The plan is to fetch dependencies with script and then create `compile.bat` to build stuff. Sounds good?

**Comment by carlkl** [comment]
what are your immediate goals beside easy installation of msys2?

**Comment by techtonik** [comment]
Automated build for CI.

**Comment by techtonik** [comment]
@carlkl Done. I had limited time to check this, but 32-bit run worked.

Found a bug - build commands include `--no-multilib` flag, which is also needed for `--fetch-only` on  32-bit systems. Should it be added for all builds? (What is the flag BTW?)

**Comment by carlkl** [comment]
@techtonik, the build flags are all well described in the builds shell script https://github.com/niXman/mingw-builds/blob/master/build. Automated builds on rackspace are already possible, see the work of @ogrisel. Personally I don't think continuus integration for mingwpy toolchains is mandantory, but you may discuss this with @ogrisel. 

The toolchains should settle on stable releases of all subprojects rather than trunk. `mingw-w64-v5.0-rc2` was released just 3 days ago and will be the base for mingwpy until v5.0 will be out.

**Comment by techtonik** [comment]
It took more that 10 hours to compile this (because I missed --jobs) and 4Gb+ of space. Still couldn't install, because run out of space.

`./build` script doesn't explain what `multilib` is - I found description only on Wikipedia pages - `GCC multilib, which allows users to install 32-bit and 64-bit libraries in parallel`.

> The toolchains should settle on stable releases of all subprojects rather than trunk.

What needs to be done to do this?

**Comment by carlkl** [comment]
@techtonik, the technical overview of the build process is part of phase2 and has to be done. Details like `--no-multilib` has to described there (on my TODO list).

Now for `bootstrap.py`: I tested it but it didn't work properly. (1) you missed `autoconf` (2) The problem with installing msys2 is, you have to manually close the window after `update-core` (that is missing in your script). An automatic msys2 install procedure would be great, but needs much more testing. Maybe the necessary steps (killing the msys2 window during installation) could be done with the help of `psutils` or the `tskill` command. (3) there is no need to start building of the toolchains with `bootstrap.py`. It should be used exclusively as an installer for msys2.

My focus is on the necessary steps for the phase2 of mingwpy rather on finetuning the msys2 installations. I vote to remove this script from the mingwpy repository and to add it again once it works as expected. In other words: development and testing of  `bootstrap.py` should be done in your fork rather than upstream.

**Comment by techtonik** [comment]
(1) is fixed. Try once more.

On (2) it is not clear if msys2 should be fixed to specific version or not? As I understood it, `update-core` updates msys2, so build no longer be repeatable. From the other side I see that dependency versions are not fixed either.

Also (2) I run bootstrap.py already from console window and it doesn't open new one. And when I start command to run in a new windows, it closes automatically. How do you run the script? Maybe [record video](https://github.com/techtonik/recordscreen/tree/windows)?

(3) it already produces build32.bat and build64.bat that are run when things are needed to be built.

**Comment by techtonik** [comment]
> I vote to remove this script from the mingwpy repository and to add it again once it works as expected.

Try it again. It should work as expected - just a single command to bootstrap build environment.

**Comment by carlkl** [comment]
I leave this PR open for now until I have time for rigorously testing. And I'm convinced that is is necessary to seperate the msys2 installation from everything else.

**Comment by techtonik** [comment]
@carlkl this is how it works right now without executing produced `build32.bat` https://ci.appveyor.com/project/techtonik/mingwpy/build/1.0.1

**Comment by carlkl** [comment]
@techtonik, did you contact @ogrisel? He is building mingwpy on rackspace.

**Comment by techtonik** [comment]
@ogrisel can you join us here?

**Comment by carlkl** [comment]
@techtonics, the main problem with the script is, you are not updating msys2 runtimes the correct way. It works today, but it may fail at any time. See https://sourceforge.net/p/msys2/wiki/MSYS2%20installation section **Updating packages**. Updating msys2 runtimes _before_ installing any msys2 packages is mandantory.

**Comment by techtonik** [comment]
@carlkl so your answer to my question about repeatable builds is that `mingwpy` doesn't need them. Okay. Let's add `update-core` then.

**Comment by techtonik** [comment]
Now I see what you mean. `update-core` hangs with `Please close this window.` message, and I need to kill the process somehow.

**Comment by mingwandroid** [comment]
MSYS2 AppVeyor CI updates itself to the latest version before proceeding. It does this in the following two lines:

https://github.com/Alexpux/MSYS2-packages/blob/master/appveyor.yml#L10-L11

**Comment by ogrisel** [comment]
> @carlkl so your answer to my question about repeatable builds is that mingwpy doesn't need them.

I would be great to have fully automated CI for the full toolchain from the upstream source but the free appveyor account is not powerful enough to build GCC in a reasonable amount of time.

**Comment by techtonik** [comment]
@ogrisel for repeatable builds just all the dependencies should be the same. For Python it would mean they are "frozen" with strict equality in `requirements.txt`. Here we can produce "frozen tarballs" with all dependencies already installed and ready to be unpacked and run for the build.

Tarballs is one possible way to speed up Appveyor builds. If GCC was written in Go, it wouldn't take so much time, so maybe it is possible to further speed up builds by copying some stuff from there. Maybe avoiding forking compiler and run it as a service. Does it support that mode? Maybe shared cache also helps to build files incrementally with every 1 hour run.

CI and Appveyor is not a primary goal for me though. The primary goal for me is to start working with toolchain with as little distractions as possible. CI is just a tool that shares the same means. So if there exists another way to do builds in independent and perhaps distributed manner - I am all ears.

**Comment by techtonik** [comment]
@mingwandroid `pacman -Sy --noconfirm pacman` + `pacman -Su --noconfirm` appears to work fine with recent pacman release - see https://github.com/Alexpux/MSYS2-pacman/pull/26

**Comment by techtonik** [comment]
@carlkl @ogrisel it works, check this out - https://ci.appveyor.com/project/techtonik/mingwpy/build/1.0.2 (AppVeyor messes up with stdout/stderr streams, so don't be surprised).

**Comment by ogrisel** [comment]
> The toolchains should settle on stable releases of all subprojects rather than trunk. mingw-w64-v5.0-rc2 was released just 3 days ago and will be the base for mingwpy until v5.0 will be out.

Is this just a matter of changing the build command from `--rt-version=trunk` to `--rt-version=v5.0-rc2` or is it more complex?

**Comment by ogrisel** [comment]
Actually the `--rt-version` flag parsing is not up to date: https://github.com/niXman/mingw-builds/blob/master/build#L237

**Comment by carlkl** [comment]
https://github.com/mingwpy/mingwpy/issues/21 for using the v5 pre-release version

**Comment by techtonik** [comment]
@ogrisel `Unsupported runtime version v5.0-rc2.`

**Comment by techtonik** [comment]
I guess ./build understands x.x.x versions only.

**Comment by carlkl** [comment]
build has to be updated, please comment on https://github.com/mingwpy/mingwpy/issues/21

**Comment by matthew-brett** [comment]
The Berkeley Institute of Data Science just bought a Windows machine that could be used for doing this kind of thing.   Any interest?

**Comment by carlkl** [comment]
I use my desktop at home for development, but such a remote machine could be used for building and deploying the toolchain. So it is definitely interesting to use such a machine.

**Comment by techtonik** [comment]
@matthew-brett I am very much interested to setup an automated build farm there, but I don't know any open source software that is targeted at Windows build automation these days.

**Comment by matthew-brett** [comment]
Carl - the BIDS machine has ssh login and you can work it via remote desktop -- do you need anything else?

Anatoly - what kind of software do you need?  I guess you could use waf or msys2 make for running the commands, and then buildbot for triggering builds - I haven't set buildbot up yet for that machine, but will do so today.

**Comment by techtonik** [comment]
Looks like `buildbot` is the only choice far Windows. I just so used to Linux containers that running anything experimental without them feels awkward. =)

**Comment by carlkl** [comment]
I intend to move @techtonik's bootstrap script to another place, so I reject this PR for now. More testing and documentation is needed.

**Comment by techtonik** [comment]
@carlkl keep me updated on the plan and I'll try to cut some part of that work for you.

**Comment by carlkl** [comment]
@techtonik, something like that: https://github.com/appveyor/ci/issues/765 should be sufficient. 
**EDIT** another possibilty: 
- install a fresh msys2 locally with all requirements
- clean up msys2 with the help of pacman 
- create an archive of your newly installed msys2 together with a small postprocess batch file to recreate the home directoy with correct name after unpacking the archive.

**Pull request closed without merging**
